/**
 * Feature Template Model
 * Pre-configured templates for quick tenant setup
 */

import { BusinessType, AccessLevel, ModuleConfiguration, TenantLimits, TenantPricing, SupportPlan } from './tenant-configuration.model';

export interface FeatureTemplate {
  id?: string;

  // Template Info
  templateName: string;
  description: string;
  businessType: BusinessType;
  accessLevel: AccessLevel;

  // Configuration
  modules: Partial<ModuleConfiguration>;
  limits: TenantLimits;
  pricing: Omit<TenantPricing, 'renewalDate' | 'nextBillingDate'>;
  supportPlan: SupportPlan;

  // Display
  displayOrder: number;
  isPopular: boolean;
  isRecommended: boolean;
  isDefault: boolean;

  // Features Highlight (for marketing)
  highlights?: string[];
  limitations?: string[];

  // Status
  isActive: boolean;
  isVisible: boolean;  // Show in tenant selection

  // Audit
  createdAt: string;
  createdBy: string;
  createdByName: string;
  updatedAt?: string;
  updatedBy?: string;
  updatedByName?: string;
}

/**
 * Pre-defined templates for common business scenarios
 */
export const PREDEFINED_TEMPLATES: Omit<FeatureTemplate, 'id' | 'createdAt' | 'createdBy' | 'createdByName'>[] = [
  // Jewellery Templates
  {
    templateName: 'Jewellery - Small Shop',
    description: 'Perfect for small jewellery shops with basic invoicing and gold rate tracking',
    businessType: 'jewellery',
    accessLevel: 'small',
    modules: {
      invoicing: true,
      estimates: true,
      customers: true,
      reports: true,
      jewelleryInventory: true,
      customOrders: false,
      oldGoldPurchase: false,
      goldRateSync: false,
    },
    limits: {
      maxUsers: 3,
      maxProducts: 500,
      maxMenuItems: 0,
      maxMedicines: 0,
      maxInvoicesPerMonth: 100,
      maxBranches: 1,
      maxStorageGB: 1,
      maxAPICallsPerDay: 0,
      maxSMSPerMonth: 0,
      maxWhatsAppPerMonth: 0,
      maxEmailsPerMonth: 100,
    },
    pricing: {
      plan: 'small',
      monthlyFee: 999,
      perUserFee: 0,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'basic',
    displayOrder: 1,
    isPopular: true,
    isRecommended: true,
    isDefault: true,
    highlights: [
      'Unlimited invoices up to 100/month',
      'Customer management',
      'Gold purity tracking',
      'Basic reports',
    ],
    limitations: [
      'No custom order management',
      'No old gold purchase',
      'Manual gold rate updates',
    ],
    isActive: true,
    isVisible: true,
  },
  {
    templateName: 'Jewellery - Advanced',
    description: 'Complete jewellery management with custom orders, old gold, and WhatsApp integration',
    businessType: 'jewellery',
    accessLevel: 'advanced',
    modules: {
      invoicing: true,
      estimates: true,
      customers: true,
      reports: true,
      jewelleryInventory: true,
      customOrders: true,
      oldGoldPurchase: true,
      goldRateSync: true,
      hallmarkTracking: true,
      schemeManagement: true,
      barcodeScanning: true,
      whatsappIntegration: true,
      advancedReports: true,
    },
    limits: {
      maxUsers: 10,
      maxProducts: 5000,
      maxMenuItems: 0,
      maxMedicines: 0,
      maxInvoicesPerMonth: 1000,
      maxBranches: 3,
      maxStorageGB: 10,
      maxAPICallsPerDay: 1000,
      maxSMSPerMonth: 500,
      maxWhatsAppPerMonth: 500,
      maxEmailsPerMonth: 1000,
    },
    pricing: {
      plan: 'advanced',
      monthlyFee: 2999,
      perUserFee: 200,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'priority',
    displayOrder: 2,
    isPopular: true,
    isRecommended: false,
    isDefault: false,
    highlights: [
      'Custom order management',
      'Old gold purchase & exchange',
      'Automatic gold rate sync',
      'WhatsApp order updates',
      'Barcode printing',
      'Advanced analytics',
    ],
    isActive: true,
    isVisible: true,
  },

  // Restaurant Templates
  {
    templateName: 'Restaurant - Small',
    description: 'Essential features for small restaurants with KOT and table management',
    businessType: 'restaurant',
    accessLevel: 'small',
    modules: {
      menuManagement: true,
      kotSystem: true,
      tableManagement: true,
      invoicing: true,
      customers: true,
      reports: true,
    },
    limits: {
      maxUsers: 3,
      maxProducts: 0,
      maxMenuItems: 100,
      maxMedicines: 0,
      maxInvoicesPerMonth: 100,
      maxBranches: 1,
      maxStorageGB: 1,
      maxAPICallsPerDay: 0,
      maxSMSPerMonth: 0,
      maxWhatsAppPerMonth: 0,
      maxEmailsPerMonth: 100,
    },
    pricing: {
      plan: 'small',
      monthlyFee: 1499,
      perUserFee: 0,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'basic',
    displayOrder: 3,
    isPopular: true,
    isRecommended: true,
    isDefault: true,
    highlights: [
      'Up to 100 menu items',
      'Up to 20 tables',
      'KOT system',
      'Dine-in & takeaway',
    ],
    limitations: [
      'No kitchen display system',
      'No online ordering',
      'No recipe costing',
    ],
    isActive: true,
    isVisible: true,
  },
  {
    templateName: 'Restaurant - Advanced',
    description: 'Complete restaurant management with KDS, delivery, and online ordering',
    businessType: 'restaurant',
    accessLevel: 'advanced',
    modules: {
      menuManagement: true,
      kotSystem: true,
      tableManagement: true,
      kitchenDisplay: true,
      tableReservations: true,
      deliveryManagement: true,
      recipeCostManagement: true,
      onlineOrdering: true,
      invoicing: true,
      customers: true,
      reports: true,
      advancedReports: true,
      whatsappIntegration: true,
    },
    limits: {
      maxUsers: 10,
      maxProducts: 0,
      maxMenuItems: 500,
      maxMedicines: 0,
      maxInvoicesPerMonth: 1000,
      maxBranches: 3,
      maxStorageGB: 10,
      maxAPICallsPerDay: 1000,
      maxSMSPerMonth: 500,
      maxWhatsAppPerMonth: 500,
      maxEmailsPerMonth: 1000,
    },
    pricing: {
      plan: 'advanced',
      monthlyFee: 4999,
      perUserFee: 200,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'priority',
    displayOrder: 4,
    isPopular: true,
    isRecommended: false,
    isDefault: false,
    highlights: [
      'Unlimited menu items',
      'Kitchen Display System',
      'Table reservations',
      'Delivery management',
      'Recipe costing',
      'Online ordering',
    ],
    isActive: true,
    isVisible: true,
  },

  // Medical Shop Templates
  {
    templateName: 'Medical Shop - Small',
    description: 'Essential pharmacy management with expiry tracking and Schedule H compliance',
    businessType: 'medical',
    accessLevel: 'small',
    modules: {
      medicineInventory: true,
      invoicing: true,
      customers: true,
      reports: true,
      expiryManagement: true,
      scheduleHCompliance: true,
    },
    limits: {
      maxUsers: 3,
      maxProducts: 0,
      maxMenuItems: 0,
      maxMedicines: 500,
      maxInvoicesPerMonth: 100,
      maxBranches: 1,
      maxStorageGB: 1,
      maxAPICallsPerDay: 0,
      maxSMSPerMonth: 0,
      maxWhatsAppPerMonth: 0,
      maxEmailsPerMonth: 100,
    },
    pricing: {
      plan: 'small',
      monthlyFee: 999,
      perUserFee: 0,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'basic',
    displayOrder: 5,
    isPopular: true,
    isRecommended: true,
    isDefault: true,
    highlights: [
      'Up to 500 medicines',
      'Expiry alerts',
      'Schedule H compliance',
      'Drug register',
    ],
    limitations: [
      'No batch tracking',
      'No prescription management',
      'No barcode scanning',
    ],
    isActive: true,
    isVisible: true,
  },
  {
    templateName: 'Medical Shop - Advanced',
    description: 'Complete pharmacy with batch tracking, prescriptions, and barcode scanning',
    businessType: 'medical',
    accessLevel: 'advanced',
    modules: {
      medicineInventory: true,
      batchTracking: true,
      prescriptionManagement: true,
      expiryManagement: true,
      scheduleHCompliance: true,
      purchaseOrders: true,
      barcodeScanning: true,
      drugInteractionWarnings: true,
      invoicing: true,
      customers: true,
      reports: true,
      advancedReports: true,
      whatsappIntegration: true,
    },
    limits: {
      maxUsers: 10,
      maxProducts: 0,
      maxMenuItems: 0,
      maxMedicines: 5000,
      maxInvoicesPerMonth: 1000,
      maxBranches: 3,
      maxStorageGB: 10,
      maxAPICallsPerDay: 1000,
      maxSMSPerMonth: 500,
      maxWhatsAppPerMonth: 500,
      maxEmailsPerMonth: 1000,
    },
    pricing: {
      plan: 'advanced',
      monthlyFee: 2999,
      perUserFee: 200,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'priority',
    displayOrder: 6,
    isPopular: true,
    isRecommended: false,
    isDefault: false,
    highlights: [
      'Unlimited medicines',
      'Batch-wise tracking',
      'Prescription management',
      'Barcode scanning',
      'Purchase orders',
      'Drug interaction warnings',
    ],
    isActive: true,
    isVisible: true,
  },

  // Retail Templates
  {
    templateName: 'Retail Store - Small',
    description: 'Simple POS for small retail shops',
    businessType: 'retail',
    accessLevel: 'small',
    modules: {
      retailPOS: true,
      customers: true,
      invoicing: true,
      reports: true,
      inventory: true,
    },
    limits: {
      maxUsers: 3,
      maxProducts: 500,
      maxMenuItems: 0,
      maxMedicines: 0,
      maxInvoicesPerMonth: 100,
      maxBranches: 1,
      maxStorageGB: 1,
      maxAPICallsPerDay: 0,
      maxSMSPerMonth: 0,
      maxWhatsAppPerMonth: 0,
      maxEmailsPerMonth: 100,
    },
    pricing: {
      plan: 'small',
      monthlyFee: 999,
      perUserFee: 0,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'basic',
    displayOrder: 7,
    isPopular: true,
    isRecommended: true,
    isDefault: true,
    highlights: [
      'Up to 500 products',
      'Quick billing',
      'Stock management',
      'Customer database',
    ],
    limitations: [
      'Cash payment only',
      'No barcode scanning',
      'No loyalty program',
    ],
    isActive: true,
    isVisible: true,
  },
  {
    templateName: 'Retail Store - Advanced',
    description: 'Complete retail POS with barcode, loyalty, and promotions',
    businessType: 'retail',
    accessLevel: 'advanced',
    modules: {
      retailPOS: true,
      barcodeScanning: true,
      loyaltyProgram: true,
      promotions: true,
      customerCredit: true,
      multiPayment: true,
      inventory: true,
      customers: true,
      invoicing: true,
      reports: true,
      advancedReports: true,
      whatsappIntegration: true,
      smsNotifications: true,
    },
    limits: {
      maxUsers: 10,
      maxProducts: 5000,
      maxMenuItems: 0,
      maxMedicines: 0,
      maxInvoicesPerMonth: 1000,
      maxBranches: 3,
      maxStorageGB: 10,
      maxAPICallsPerDay: 1000,
      maxSMSPerMonth: 500,
      maxWhatsAppPerMonth: 500,
      maxEmailsPerMonth: 1000,
    },
    pricing: {
      plan: 'advanced',
      monthlyFee: 2999,
      perUserFee: 200,
      perTransactionFee: 0,
      setupFee: 0,
      billingCycle: 'monthly',
      autoRenewal: true,
      discountPercent: 0,
      extraUserFee: 200,
      extraBranchFee: 500,
      extraStorageFee: 300,
      smsCostPerUnit: 0.10,
      whatsappCostPerUnit: 0.25,
      emailCostPerUnit: 0,
    },
    supportPlan: 'priority',
    displayOrder: 8,
    isPopular: true,
    isRecommended: false,
    isDefault: false,
    highlights: [
      'Unlimited products',
      'Barcode scanning',
      'Loyalty program',
      'Promotions & offers',
      'Multi-payment support',
      'WhatsApp promotions',
    ],
    isActive: true,
    isVisible: true,
  },
];
